### ISSUE TITLE
Get it working with IR enabled

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/auto-service-kt#4]
This fails internally in kotlinc when I test it. Also effectively blocks updating to Kotlin 1.5.0

```
Caused by: java.lang.AssertionError: IR backend shouldn't call KotlinTypeMapper.mapType: TestClass
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.kt:271)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapClass(KotlinTypeMapper.kt:232)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:300)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:289)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	... 74 more
```

**Comment by ZacSweers** [comment]
Pending https://youtrack.jetbrains.com/issue/KT-46494
